# Generated by Django 5.2.1 on 2025-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empn0', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
